### ISSUE TITLE
Contradicting info

### ISSUE THREAD

**Issue by H4ckerxx44** [Ruu3f/projects#2]
So, by your GitHub profile description you are:
> I'm a full-stack developer with a passion for open-source projects.

Although, you have nothing ~not a single public repository~ open source about your minecraft mods let alone you have set your activity on GitHub to be private, that is not really what is generally something you do if you are passioned about open-source projects.

For example, the [Obsidian Tools](https://modrinth.com/mod/obsidiantools) mods is closed source.
In fact, I have just realized that _none_ of the mods you have on your [Modrinth profile](https://modrinth.com/user/Ruu3f) are open source, that is _very_ contradicting your description and, by extent, what you publicly make of yourself.

Furthermore, on your [buymeacoffee](https://buymeacoffee.com/ruu3f) page, you claim
> Hey, I'm a code enthusiast *who enjoys creating open-source projects.* I've developed numerous projects spanning various categories.

Do you, though?
Because, if so, you would have ~projects on your GitHub page...~ made your Minecraft mods open source, I would guess.

Why?

**Comment by H4ckerxx44** [comment]
I appreciate the answer, especially because the answer is not something I have expected.

I would like to ask you why you are not open-sourcing your Minecraft mods though, I do not imply you have no right to keep them private, I am genuinely curious on what your reasons are, if you have any "specific" ones, preference surely is something totally valid too!

**Comment by H4ckerxx44** [comment]
Surely!

My discord is `suedgeorgien`

**Comment by Ruu3f** [comment]
Alright.
