### ISSUE TITLE
ZAC suggestion: ruined/normal zombie related structures

### ISSUE THREAD

**Issue by NotoriousCoke** [Ruu3f/projects#3]
It could be ruined/non-ruined buildings like factories, facilities, military bases, etc. The perfect necessity for a zombie apoc.

I know it doesn't 100 fit your mod theme, but I can't find any other mod that does this. Please I beg of you.

**Comment by Ruu3f** [comment]
Actually, that is not a bad idea, but instead of adding it to Zombie Apocalypse Core, I could make it a separate mod since Zombie Apocalypse Core is meant for having only the core parts.
But again, I'm not good at building; the structures will not look good.

**Comment by NotoriousCoke** [comment]
PLEASE DAWG, ain no one doing anything like this 😭. Building shouldn't be much of an issue with how many tutorials there are on youtube. The world needs this fr 🫡

**Comment by Ruu3f** [comment]
Well, I can try.

**Comment by Ruu3f** [comment]
I tried it and failed miserably, Sorry dude.

**Comment by NotoriousCoke** [comment]
All good and don't worry bout it. Appreciate you trying.
