### ISSUE TITLE
Can't remove skeletons from disabled mobs list

### ISSUE THREAD

**Issue by Numomoo** [Ruu3f/projects#6]
### Project

Zombie Apocalypse Core

### Bug Description

Love the mod, just what I've been looking for but I don't want Skeletons, Creepers, and Spiders to be removed. When I go to use the /disabledmobs add/remove command it works for every other mob but skeletons. Skeletons are always removed for some reason.

### Information

- Minecraft version 1.20.1
- Loader  Forge 47.3.11
- Mod version 1.2.1

### Steps to Reproduce

- 1. get into a game
- 2. use the "/disabledmobs add/remove Skeletons command"
- 3. use the "/viewdisabledmobs command" and you should see skeletons don't change

**Comment by Ruu3f** [comment]
Fixed it, the new version of the mod will be ported to other versions and uploaded tomorrow.
